services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_library
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=28_571&BvKv&
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'select 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
